### ISSUE TITLE
Regarding level code feature removal

### ISSUE THREAD

**Issue by Niki4tap** [RocketRace/robot-is-you#12]
# Hello, I noticed that in (semi) recent commit, feature of the bot displaying levels from level code was silently removed. So, I have 3 questions right now:

* Why the commit was so strange?
* If the code for it still there, will this feature be supported in the future?
* I would like to contribute, but not sure how.

## Firstly, commit regarding removal of this feature (881955c24c82328d5dd50152af7e234a1bf0b3c7) was very weird.

Why is it marked as a hotfix? It is clearly not.

Personally, I don't think that's a good thing to call a commit that way, as people interested in your project will incorrectly assume, that this commit was fixing some bug, and not removing a whole feature.
I know that this feature was discarded, because of the new update in baba is you game, that somehow affected downloading/uploading levels, and now bot is creating wrong tiles/rules, so it wouldn't actually represent the level correctly, and that's why I think it was removed.

## The future of left out code

Is the code going to be fixed or is it going to be abandoned?

### In option 2 (which is pretty bad way), I would recommend (at least) removing this line from src/cogs/global.py:
```py
* Checks if the input matches a custom level code (e.g. "ABCD-1234")
```
Because, obviously, feature was removed, and bot is saying that level is not found although, it should be.

### In option 1, I would like to contribute, but I don't really know what to do:

I don't know what exactly was changed and how to rework the present code (because I think most of it can be reused), so it would work correctly.

I think that issue might be either in parsing of level (.l or .ld files) or IDs of some objects might have been changed, so the bot interprets them incorrectly as different tile/rule.

Anyways, that's basically it.

**Comment by RocketRace** [comment]
Hi! Thanks for reminding me. The custom level renderer was accidentally committed to master and I didn't notice until later, but will be added back once it works. Currently there's a bug with applying proper tile changes, leading to the wrong sprites etc. I think I know how to fix this.

Thanks for the heads up with the docstring, it's definitely misleading
