### ISSUE TITLE
Facing appears inactive when using the +level command

### ISSUE THREAD

**Issue by DarkBrick** [RocketRace/robot-is-you#14]
![image](https://user-images.githubusercontent.com/63005558/121949102-63327780-cd58-11eb-9b9e-cdc2a949ce77.png)

**Comment by DarkBrick** [comment]
Issue seems to be only for custom levels btw, main game works fine

**Comment by RocketRace** [comment]
What level code is this?

**Comment by DarkBrick** [comment]
Forgot about this but it happens with several codes i tried, this particular level is NBQY-NB7M

**Comment by DarkBrick** [comment]
![image](https://user-images.githubusercontent.com/63005558/123541017-6b1fed80-d742-11eb-84fe-68dc769f6002.png)
When you create a new level the issue still appears (DPL8-VUQR)

**Comment by CenTdemeern1** [comment]
I checked and confirmed that this is indeed an issue.
And an interesting one at that.
As DarkBrick says, it doesn't happen in levels in the main game.
https://media.discordapp.net/attachments/801128414350147636/858654127931392010/SPOILER_227level.gif

**Comment by CenTdemeern1** [comment]
Has this been addressed?

**Comment by CenTdemeern1** [comment]
Nope, issue seems to have been resolved.

**Comment by CenTdemeern1** [comment]
@RocketRace you can close this issue now

**Comment by RocketRace** [comment]
Seems to be resolved now.
